accountWhitelist:
  - 123445678901
assumeRoles:
  123445678901: omnisssm-iam-role
instanceRole: null
maxRetries: 10
queueName: omnissm-deferred-actions-queue
registrationsTable: omnissm-registrations
resourceDeletedSNSTopic: null
resourceTags:
  - Name
  - OwnerContact
  - App
s3DownloadRole: null
snsPublishRole: null
